# Generated by Django 3.2.13 on 2022-06-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreGraphRestAPI_Products', '0001_initial'),
        ('coreGraphRestAPI_Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_carts', to='coreGraphRestAPI_Products.product'),
        ),
    ]
