# Generated by Django 3.2.13 on 2022-06-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreGraphRestAPI_Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreGraphRestAPI_Products', '0001_initial'),
        ('coreGraphRestAPI_Businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='coreGraphRestAPI_Users.imageupload'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments_on_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_business', to='coreGraphRestAPI_Businesses.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='coreGraphRestAPI_Products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='coreGraphRestAPI_Products.productcomment'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='coreGraphRestAPI_Products.productimage'),
        ),
    ]
