# Generated by Django 3.2.13 on 2022-06-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreGraphRestAPI_Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreGraphRestAPI_Businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_business', to='coreGraphRestAPI_Users.imageupload'),
        ),
        migrations.AddField(
            model_name='businesscomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments_on_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='business_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_address', to='coreGraphRestAPI_Businesses.businessaddress'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_comments', to='coreGraphRestAPI_Businesses.businesscomment'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_images', to='coreGraphRestAPI_Businesses.businessimage'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
